security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        users_in_memory:
            memory:
                users:
                    admin: { password: '$argon2i$v=19$m=16,t=2,p=1$RDRtaGpnZzY4MDJGdk9uNw$zqD0qNFt4QgQ3O2oA+E1KA', roles: ['ROLE_ADMIN']}
                    julia: { password: '$argon2i$v=19$m=16,t=2,p=1$RDRtaGpnZzY4MDJGdk9uNw$zqD0qNFt4QgQ3O2oA+E1KA', roles: ['ROLE_SUPER_ADMIN']}
                    bob: { password: '$argon2i$v=19$m=16,t=2,p=1$RDRtaGpnZzY4MDJGdk9uNw$zqD0qNFt4QgQ3O2oA+E1KA', roles: ['ROLE_CARTOGRAPHER']}
                    alicja: { password: '$argon2i$v=19$m=16,t=2,p=1$RDRtaGpnZzY4MDJGdk9uNw$zqD0qNFt4QgQ3O2oA+E1KA', roles: ['ROLE_MEASURER']}
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
            form_login:
                login_path: login
                check_path: login
            logout:
                path: app_logout
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy: 
        ROLE_ADMIN:
            - ROLE_WEATHER_EDIT
            - ROLE_CITY_EDIT
        ROLE_SUPER_ADMIN:
            - ROLE_WEATHER_CREATE
            - ROLE_WEATHER_DELETE
            - ROLE_CITY_CREATE
            - ROLE_CITY_DELETE
        ROLE_MEASURER:
            - ROLE_WEATHER_CREATE
            - ROLE_WEATHER_EDIT
            - ROLE_WEATHER_DELETE
        ROLE_CARTOGRAPHER:
            - ROLE_CITY_CREATE
            - ROLE_CITY_EDIT
            - ROLE_CITY_DELETE

