App\Entity\City:
  properties:
    latitude:
      - Range:
          min: -90
          max: 90
          groups: ['new', 'edit']
    longitude:
      - Range:
          min: -180
          max: 180
          groups: ['new', 'edit']

App\Entity\Weather:
  properties:
    temperature:
      - Range:
          min: -100
          max: 100
          groups: ['new', 'edit']
      - NotBlank: ~
    date:
      - NotBlank: ~
    image_id:
      - Range:
          min: 0
          max: 16
          groups: ['new', 'edit']
    temperature_feel:
      - Range:
          min: -100
          max: 100
          groups: ['new', 'edit']
    wind_speed:
      - Range:
          min: 0
          max: 500
          groups: ['new', 'edit']
    precipitation:
      - Range:
          min: 0
          max: 2000
          groups: ['new', 'edit']
    humidity:
      - Range:
          min: 0
          max: 1
          groups: ['new', 'edit']
    pressure:
      - Range:
          min: 960
          max: 1065
          groups: ['new', 'edit']